principal = input("Please Input Principal: ")
interest = input("Please Input Interest Rate as a Decimal:")
term = input("Please Enter The Term of the Loan in Years:")
compound = input("Please Enter The Number of Payments Per Year:")
principalint = int(principal)
interestfloat = float(interest)
termint = int(term)
compoundint = int(compound)
total = principalint*(1+(interestfloat/compoundint))**(compoundint*termint)
print("Principal: " + principal)
print("Rate: " + interest)
print("Term: " + term)
print("Compound: " + compound)
print("Total paid after " + term + " years: " + str(total))
interestpaid = total-principalint
print("Interest paid after " + term + "years: " + str(interestpaid))
