principal = input("Input Principal: ")
total = input("Input Total Amount Paid: ")
term = input("Input Term in Years: ")
compound = input("Input Number of Payments Per Year: ")
principalint = int(principal)
totalint = float(total)
termint = int(term)
compoundint = int(compound)
rate = compoundint*((totalint/principalint)**(1/(termint*compoundint))-1)
ratestr = str(rate)
print("The interest rate on a loan for " + principal + " that cost " + total + " over " + term + " years is: " + ratestr)
