name: en685621
channels:
  - conda-forge
dependencies:
  - python=3.9.1
  - numpy=1.21.4
  - scipy=1.8.1
  - matplotlib=3.4.3
  - seaborn=0.11.2
  - jupyter
  - jupyterlab
  - ipython=7.29.0
  - ipykernel=6.5.0
  - pandas=1.3.5
  - scikit-learn=1.1.2
  - keras=2.7.0
  - plotly=5.5.0